# Generated by Django 6.0.3 on 2026-03-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='image',
            field=models.ImageField(blank=True, help_text='small png image preferable.', null=True, upload_to='facilities'),
        ),
    ]
