# Generated by Django 6.0.3 on 2026-03-31 09:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('no_of_rooms', models.CharField(default=1, max_length=100)),
                ('adults', models.CharField(default=2, max_length=100)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('guest_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('special_request', models.TextField(blank=True, null=True)),
                ('total_pricing', models.CharField(blank=True, max_length=100, null=True)),
                ('booked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.room')),
            ],
            options={
                'verbose_name': 'Room Booking',
                'verbose_name_plural': 'Room Booking',
            },
        ),
    ]
