# Generated by Django 5.2.5 on 2025-08-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='description',
        ),
        migrations.AlterField(
            model_name='offer',
            name='ordering',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
