# Generated by Django 6.0.1 on 2026-02-09 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_remove_offer_description_alter_offer_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='sub_title',
        ),
    ]
