# Generated by Django 6.0.3 on 2026-03-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_remove_offer_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='sub_title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
