# Generated by Django 5.2 on 2025-05-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(default='test.jpg', help_text='471*220', upload_to='services'),
            preserve_default=False,
        ),
    ]
