# Generated by Django 5.2 on 2025-05-06 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_services_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='image',
        ),
    ]
