# Generated by Django 5.2 on 2025-05-07 16:35

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_services_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
