# Generated by Django 5.2 on 2025-05-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('sub_heading', models.CharField(max_length=255)),
                ('featured_image', models.ImageField(blank=True, default='', null=True, upload_to='about')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='PrincipalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('sub_heading', models.CharField(max_length=255)),
                ('featured_image', models.ImageField(blank=True, default='', null=True, upload_to='principal')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Message From Principal',
                'verbose_name_plural': 'Message From Principal',
            },
        ),
        migrations.CreateModel(
            name='Whyus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('featured_image', models.ImageField(blank=True, default='', null=True, upload_to='image')),
                ('description', models.TextField()),
                ('skill_development', models.TextField()),
                ('experienced_teachers', models.TextField()),
                ('career_opportunities', models.TextField()),
            ],
            options={
                'verbose_name': 'Why Us',
                'verbose_name_plural': 'Why Us',
            },
        ),
    ]
