# Generated by Django 5.2 on 2025-05-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0003_legaldocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('featured_image', models.ImageField(blank=True, default='', null=True, upload_to='image')),
                ('description', models.TextField()),
                ('skill_development', models.TextField()),
                ('experienced_teachers', models.TextField()),
                ('career_opportunities', models.TextField()),
            ],
            options={
                'verbose_name': 'Vision & Mission',
                'verbose_name_plural': 'Vision & Mission',
            },
        ),
        migrations.RenameModel(
            old_name='PrincipalMessage',
            new_name='ChairmanMessage',
        ),
        migrations.RenameModel(
            old_name='Whyus',
            new_name='Goals',
        ),
        migrations.AlterModelOptions(
            name='chairmanmessage',
            options={'verbose_name': 'Message From Chairman', 'verbose_name_plural': 'Message From Chairman'},
        ),
        migrations.AlterModelOptions(
            name='goals',
            options={'verbose_name': 'Goals & Core Values', 'verbose_name_plural': 'Goals & Core Values'},
        ),
    ]
