# Generated by Django 5.2 on 2025-05-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0004_vision_rename_principalmessage_chairmanmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='recruitment')),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recruitment Process FLow',
                'verbose_name_plural': 'Recruitment Process FLow',
            },
        ),
    ]
