# Generated by Django 5.2 on 2025-05-06 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0005_recruitmentprocess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goals',
            name='career_opportunities',
        ),
        migrations.RemoveField(
            model_name='goals',
            name='experienced_teachers',
        ),
        migrations.RemoveField(
            model_name='goals',
            name='skill_development',
        ),
        migrations.RemoveField(
            model_name='vision',
            name='career_opportunities',
        ),
        migrations.RemoveField(
            model_name='vision',
            name='experienced_teachers',
        ),
        migrations.RemoveField(
            model_name='vision',
            name='skill_development',
        ),
    ]
