# Generated by Django 5.2 on 2025-05-06 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0006_remove_goals_career_opportunities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitmentprocess',
            name='ordering',
        ),
    ]
