# Generated by Django 5.2 on 2025-05-06 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0007_remove_recruitmentprocess_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legaldocument',
            name='ordering',
        ),
    ]
