# Generated by Django 5.2 on 2025-05-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0008_remove_legaldocument_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('featured_image', models.ImageField(blank=True, default='', null=True, upload_to='about')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Why us',
                'verbose_name_plural': 'Why us',
            },
        ),
    ]
