# Generated by Django 6.0.1 on 2026-01-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0010_alter_about_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whyus',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='whyus',
            name='image_icon',
            field=models.ImageField(blank=True, default='', null=True, upload_to='about'),
        ),
        migrations.AddField(
            model_name='whyus',
            name='short_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
