# Generated by Django 5.2.5 on 2025-12-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='distance',
            field=models.CharField(blank=True, help_text='eg. 2 km', max_length=255, null=True),
        ),
    ]
